config/routes.rb
Rails.application.routes.draw do
  get 'reservations/create'

  get 'users/show'

  devise_for :users, :path => '',
                    path_names: { :sign_in => 'Login', :sign_out => 'logout', :edit => 'profile'},
                    controllers: { registrations: :registrations,
                                   confirmations: :confirmations
                     }
  root 'pages#home'

  resources :users , only: [ :show ]
  resources :rooms, path: 'listings' do
    resources :reservations, only: [ :create ]
    resources :reviews, only: [:create, :destroy]
  end
  resources :photos

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/preload', to: 'reservations#preload'
  get '/preview', to: 'reservations#preview'
  get 'your_trips', to: "reservations#your_trips", path: 'my_trips'
  get '/your_reservations', to: 'reservations#your_reservations', path: 'my_reservations'

  get '/search', to: 'pages#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord

  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'

  belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :recipient_id

  scope :involving, -> (user) do
    where("conversations.sender_id = ? OR conversations.recipient_id = ?", user.id, user.id)
  end

  scope :between, -> (sender_id, recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR (conversations.sender_id = ? AND conversations.recipient_id = ?)", sender_id, recipient_id, recipient_id, sender_id)
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :content, :conversation_id, :user_id
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :room

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :photos
  has_many :reservations
  has_many :reviews

  validates :home_type, presence: true
  validates :accomodate, presence: true
  validates :bed_room, presence: true
  validates :bath_room, presence: true
  validates :listing_name, presence: true, length: { maximum: 75 }
  validates :summary, presence:true, length: { maximum: 600 }
  validates :address, presence: true
  validates :price, numericality: { only_integer: true, greater_than: 5 }

  geocoded_by :address
  after_validation :geocode , if: :address_changed?

  def average_rating
    reviews.count == 0 ? 0 : reviews.average(:star).round(2)
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms
  has_many :reservations
  has_many :reviews

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates :fullname, presence: true, length: { maximum: 50 }

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @rooms = Room.order("RANDOM()").limit(3)
  end

  def search
      if params[:search].present? && params[:search].strip != ""
         session[:aiirbnb_search] = params[:search]
      end

      arrResult = Array.new

      if session[:aiirbnb_search] && session[:aiirbnb_search] != ""
         @rooms_address = Room.where(active: true).near(session[:aiirbnb_search], 5, order:'distance')
      else
         @rooms_address = Room.where(active: true).all
      end

      @search = @rooms_address.ransack(params[:q])
      @rooms = @search.result

      @arrRooms = @rooms.to_a

      if (params[:start_date] && params[:end_date] && !params[:start_date].empty? & !params[:end_date].empty?)
         start_date = Date.parse(params[:start_date])
         end_date = Date.parse(params[:end_date])

         @rooms.each do |room|
            not_available = room.reservations.where("(? <= start_date AND start_date <= ?) OR
            (? <= end_date AND end_date <= ?) OR (start_date < ? AND ? < end_date)", start_date, end_date,
            start_date, end_date, start_date, end_date).limit(1)

            if not_available.length > 0
               @arrRooms.delete(room)
            end
         end
      end
   end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!

  def preload
       room = Room.find(params[:room_id])
       today = Date.today
       reservations = room.reservations.where("start_date >= ? OR end_date >= ?", today, today)

       render json: reservations
    end

    def preview
        start_date = Date.parse(params[:start_date])
        end_date = Date.parse(params[:end_date])

        output = {
            conflict: is_conflict(start_date, end_date)
        }

        render json: output
    end

  def create
    @reservation = current_user.reservations.create(reservation_params)
    redirect_to @reservation.room, notice: "Your reservation have been accepted"
  end

  def your_trips
    @trips = current_user.reservations
  end

  def your_reservations
    @rooms = current_user.rooms
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :price, :total, :room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [ :show, :edit, :update ]

  before_action :authenticate_user!, exept: [ :show ]
  before_action :require_same_user, only: [ :edit, :update ]

  def index
    @rooms = current_user.rooms
  end

  def show
    @photos = @room.photos

    @booked = Reservation.where("room_id = ? AND user_id = ?", @room.id, current_user )
    if current_user
      @reviews = @room.reviews
      @hasReview = @reviews.find_by(user_id: current_user.id) if current_user
    end
  end

  def edit
    @photos = @room.photos
  end

  def update
    if @room.update(room_params)
      if params[:images]
          params[:images].each do |i|
            @room.photos.create(image: i)
          end
        end
        @photos = @room.photos
      redirect_to edit_room_path(@room), notice: "Your room is updated with success"
    else
      render :edit
    end
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      if params[:images]
          params[:images].each do |i|
            @room.photos.create(image: i)
          end
        end
        @photos = @room.photos
      redirect_to edit_room_path(@room), notice: "Your room is created with success"
    else
      render :new
    end
  end


  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:home_type, :room_type, :accomodate, :bed_room, :bath_room,
                                :listing_name, :summary, :address, :is_wifi, :is_tv, :is_closet,
                                :is_shampoo, :is_breakfast, :is_heating, :is_air, :is_kitchen, :price, :active)
  end

  def require_same_user
    if current_user.id != @room.user_id
      flash[:danger] = "You have no access to delete this room"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
    @rooms = @user.rooms
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def avatar_url(user)
    if user.avatar.present?
      user.avatar.url
    else
      'default_image.png'
    end
  end
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/reservations/_form.html.erb
<script>
    function unavailable(date) {
        dmy = date.getDate() + "-" + (date.getMonth() + 1) + "-" + date.getFullYear();
        return [$.inArray(dmy, unavailableDates) == -1];
    }
    $(function(){

        unavailableDates = [];

        $.ajax({
            url: '/preload',
            data: {'room_id': <%= @room.id %>},
            dataType: 'json',
            success: function(data) {
                $.each(data, function(arrID, arrValue){
                    for(var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date);
                    d.setDate(d.getDate() +1)) {
                        unavailableDates.push($.datepicker.formatDate('d-m-yy', d));
                    }
                })

                $('#reservation_start_date').datepicker({
                    dateFormat: 'dd-mm-yy',
                    monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août',
                    'Septembre','Octobre','Novembre','Décembre'],
                    dayNamesMin: ['D','L','M','M','J','V','S'],
                    minDate: 0,
                    maxDate: '3m',
                    beforeShowDay: unavailable,
                    onSelect: function(selected) {
                        var newdate = new Date($("#reservation_start_date").datepicker("getDate"));
                        newdate.setDate(newdate.getDate() + 1);
                        $('#reservation_end_date').datepicker("option","minDate", newdate);
                        $('#reservation_end_date').attr('disabled', false);

                        var start_date = $(this).datepicker('getDate');
                        var end_date = $('#reservation_end_date').datepicker('getDate');
                        var diff = (end_date - start_date)/1000/60/60/24;
                        var days = Math.round(diff);


                        var input = {
                            'start_date': start_date,
                            'end_date': end_date,
                            'room_id': <%= @room.id %>

                        }

                            $.ajax({
                                url: '/preview',
                                data: input,
                                success: function(data) {
                                    if (data.conflict) {
                                        $('#message').show();
                                        $('#message').text("Ces dates sont indisponibles");
                                        $('#preview').hide();
                                        $('#btn_book').attr('disabled', true);
                                    } else {
                                        $('#message').hide();
                                        $('#preview').show();
                                        $('#btn_book').attr('disabled', false);

                                        var total = days * <%= @room.price %>
                                        $('#reservation_days').text(days);
                                        $('#reservation_sum').text(total);
                                        $('#reservation_total').val(total);
                                    }

                                }
                            });

                    }
                });

                $('#reservation_end_date').datepicker({
                    dateFormat: 'dd-mm-yy',
                    monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août',
                    'Septembre','Octobre','Novembre','Décembre'],
                    dayNamesMin: ['D','L','M','M','J','V','S'],
                    minDate: 0,
                    maxDate: '3m',
                    beforeShowDay: unavailable,
                    onSelect: function(selected) {
                        $('#reservation_start_date').datepicker("option", "maxDate", selected);

                        var start_date = $('#reservation_start_date').datepicker('getDate');
                        var end_date = $(this).datepicker('getDate');
                        var diff = (end_date - start_date)/1000/60/60/24;
                        var days = Math.round(diff);


                        var input = {
                            'start_date': start_date,
                            'end_date': end_date,
                            'room_id': <%= @room.id %>

                        }

                            $.ajax({
                                url: '/preview',
                                data: input,
                                success: function(data) {
                                    if (data.conflict) {
                                        $('#message').show();
                                        $('#message').text("Ces dates sont indisponibles");
                                        $('#preview').hide();
                                        $('#btn_book').attr('disabled', true);
                                    } else {
                                        $('#message').hide();
                                        $('#preview').show();
                                        $('#btn_book').attr('disabled', false);

                                        var total = days * <%= @room.price %>
                                        $('#reservation_days').text(days);
                                        $('#reservation_sum').text(total);
                                        $('#reservation_total').val(total);
                                    }

                                }
                            });

                    }
                });

            }
        });


    });
</script>

app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

app/views/reservations/your_reservations.html.erb
<div class="row">
    <div class="col-md-3">
        <ul class="sidebar-list">
            <li class="sidebar-item"><%= link_to "Mes Listings", rooms_path, class:"sidebar-link" %></li>
            <li class="sidebar-item"><%= link_to "My Reservations", your_reservations_path, class:"sidebar-link active" %></li>
            <li class="sidebar-item"><%= link_to "My trips", your_trips_path, class:"sidebar-link " %></li>
        </ul>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading"> My trips</div>
            <div class="panel-body">
                <% @rooms.order("id DESC").each do |room| %>
                <% room.reservations.order("id DESC").each do |reservation| %>
                <div class="row">
                   <div class="col-md-2">
                       Du <%= reservation.start_date.try(:strftime, '%d.%m.%y') %> au <%= reservation.end_date.try(:strftime, '%d.%m.%y') %>
                   </div>
                   <div class="col-md-6">
                       <%= link_to room_path(reservation.room) do %>
                           <%= image_tag reservation.room.photos[0].image.url(:thumb) if reservation.room.photos.length > 0 %>
                       <% end %>
                   </div>
                   <div class="col-md-2">
                       <%= link_to user_path(reservation.room.user) do %>
                           <%= image_tag avatar_url(reservation.room.user), class:"img-circle avatar-medium" %>
                       <% end %>
                   </div>
                   <div class="col-md-2 right">
                       <h4><%= reservation.total %> €</h4>
                   </div>
                </div>
                <hr>
                <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/reservations/your_trips.html.erb
<div class="row">
    <div class="col-md-3">
        <ul class="sidebar-list">
            <li class="sidebar-item"><%= link_to "Mes Listings", rooms_path, class:"sidebar-link" %></li>
            <li class="sidebar-item"><%= link_to "My Reservations", rooms_path, class:"sidebar-link" %></li>
            <li class="sidebar-item"><%= link_to "My trips", your_trips_path, class:"sidebar-link active" %></li>
        </ul>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading"> My trips</div>
            <div class="panel-body">
                <% @trips.order("id DESC").each do |trip| %>
                <div class="row">
                   <div class="col-md-2">
                       Du <%= trip.start_date.try(:strftime, '%d.%m.%y') %> au <%= trip.end_date.try(:strftime, '%d.%m.%y') %>
                   </div>
                   <div class="col-md-6">
                       <%= link_to room_path(trip.room) do %>
                           <%= image_tag trip.room.photos[0].image.url(:thumb) if trip.room.photos.length > 0 %>
                       <% end %>
                   </div>
                   <div class="col-md-2">
                       <%= link_to user_path(trip.room.user) do %>
                           <%= image_tag avatar_url(trip.room.user), class:"img-circle avatar-medium" %>
                       <% end %>
                   </div>
                   <div class="col-md-2 right">
                       <h4><%= trip.total %> €</h4>
                   </div>
                </div>
                <hr>
                <% end %>
            </div>
        </div>
    </div>
</div>