config/routes.rb
Rails.application.routes.draw do
  get 'reservations/create'

  get 'users/show'

  devise_for :users, :path => '',
                    path_names: { :sign_in => 'Login', :sign_out => 'logout', :edit => 'profile'},
                    controllers: { registrations: :registrations,
                                   confirmations: :confirmations
                     }
  root 'pages#home'

  resources :users , only: [ :show ]
  resources :rooms, path: 'listings' do
    resources :reservations, only: [ :create ]
    resources :reviews, only: [:create, :destroy]
  end
  resources :photos

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/preload', to: 'reservations#preload'
  get '/preview', to: 'reservations#preview'
  get 'your_trips', to: "reservations#your_trips", path: 'my_trips'
  get '/your_reservations', to: 'reservations#your_reservations', path: 'my_reservations'

  get '/search', to: 'pages#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord

  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'

  belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :recipient_id

  scope :involving, -> (user) do
    where("conversations.sender_id = ? OR conversations.recipient_id = ?", user.id, user.id)
  end

  scope :between, -> (sender_id, recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR (conversations.sender_id = ? AND conversations.recipient_id = ?)", sender_id, recipient_id, recipient_id, sender_id)
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :content, :conversation_id, :user_id
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :room

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :photos
  has_many :reservations
  has_many :reviews

  validates :home_type, presence: true
  validates :accomodate, presence: true
  validates :bed_room, presence: true
  validates :bath_room, presence: true
  validates :listing_name, presence: true, length: { maximum: 75 }
  validates :summary, presence:true, length: { maximum: 600 }
  validates :address, presence: true
  validates :price, numericality: { only_integer: true, greater_than: 5 }

  geocoded_by :address
  after_validation :geocode , if: :address_changed?

  def average_rating
    reviews.count == 0 ? 0 : reviews.average(:star).round(2)
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms
  has_many :reservations
  has_many :reviews

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates :fullname, presence: true, length: { maximum: 50 }

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @rooms = Room.order("RANDOM()").limit(3)
  end

  def search
      if params[:search].present? && params[:search].strip != ""
         session[:aiirbnb_search] = params[:search]
      end

      arrResult = Array.new

      if session[:aiirbnb_search] && session[:aiirbnb_search] != ""
         @rooms_address = Room.where(active: true).near(session[:aiirbnb_search], 5, order:'distance')
      else
         @rooms_address = Room.where(active: true).all
      end

      @search = @rooms_address.ransack(params[:q])
      @rooms = @search.result

      @arrRooms = @rooms.to_a

      if (params[:start_date] && params[:end_date] && !params[:start_date].empty? & !params[:end_date].empty?)
         start_date = Date.parse(params[:start_date])
         end_date = Date.parse(params[:end_date])

         @rooms.each do |room|
            not_available = room.reservations.where("(? <= start_date AND start_date <= ?) OR
            (? <= end_date AND end_date <= ?) OR (start_date < ? AND ? < end_date)", start_date, end_date,
            start_date, end_date, start_date, end_date).limit(1)

            if not_available.length > 0
               @arrRooms.delete(room)
            end
         end
      end
   end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [ :show, :edit, :update ]

  before_action :authenticate_user!, exept: [ :show ]
  before_action :require_same_user, only: [ :edit, :update ]

  def index
    @rooms = current_user.rooms
  end

  def show
    @photos = @room.photos

    @booked = Reservation.where("room_id = ? AND user_id = ?", @room.id, current_user )
    if current_user
      @reviews = @room.reviews
      @hasReview = @reviews.find_by(user_id: current_user.id) if current_user
    end
  end

  def edit
    @photos = @room.photos
  end

  def update
    if @room.update(room_params)
      if params[:images]
          params[:images].each do |i|
            @room.photos.create(image: i)
          end
        end
        @photos = @room.photos
      redirect_to edit_room_path(@room), notice: "Your room is updated with success"
    else
      render :edit
    end
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      if params[:images]
          params[:images].each do |i|
            @room.photos.create(image: i)
          end
        end
        @photos = @room.photos
      redirect_to edit_room_path(@room), notice: "Your room is created with success"
    else
      render :new
    end
  end


  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:home_type, :room_type, :accomodate, :bed_room, :bath_room,
                                :listing_name, :summary, :address, :is_wifi, :is_tv, :is_closet,
                                :is_shampoo, :is_breakfast, :is_heating, :is_air, :is_kitchen, :price, :active)
  end

  def require_same_user
    if current_user.id != @room.user_id
      flash[:danger] = "You have no access to delete this room"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
    @rooms = @user.rooms
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def avatar_url(user)
    if user.avatar.present?
      user.avatar.url
    else
      'default_image.png'
    end
  end
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Airbnb", root_path, class: "navbar-brand navbar-left"%>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <%= form_tag search_path, class: "navbar-form navbar-left", method: :get do %>
            <div class="search">
              <span class="fa fa-search"></span>
              <%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
            </div>
          <% end %>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to new_room_path do %>
                <i class="fa fa-home fa-lg">Become a host</i>
              <% end %>
            </li>
            <li>
              <%= link_to conversations_path do %>
                Message
              <% end %>
            </li>
            <% if user_signed_in? %>

                 <li class="dropdown">
                   <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %><%= current_user.fullname %> <span class="caret"></span></a>
                   <ul class="dropdown-menu">
                     <li><%= link_to "My Travels", your_trips_path %></li>
                     <li><%= link_to "My Reservations", your_reservations_path %></li>
                     <li><%= link_to "My Listings", rooms_path %></li>
                     <li role="separator" class="divider"></li>
                     <li><%= link_to "My Profile", users_show_path %></li>
                     <li><%= link_to "Edit my Profile", edit_user_registration_path %></li>
                     <li role="separator" class="divider"></li>
                     <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" } %></li>
                   </ul>
                 </li>
            <% else %>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
                <li><%= link_to "Sign In", new_user_session_path %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <%= favicon_link_tag '/assets/images/favicon.ico' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>

      <%= render 'shared/message' %>

      <div class="container">
        <%= yield %>
      </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="text-center">
      <h1>Reserve unique accommodations and live your destination as a resident</h1>
    </div>
  </div>
</div>

<br>

<%= form_tag search_path, method: :get do %>
  <div class="row">
    <div class="col-md-6">
      <%= text_field_tag :search, params[:search], placeholder: "Where? Destination, City, Address",
      class: "form-control" %>
    </div>
    <div class="col-md-2">
      <%= text_field_tag :start_date, params[:start_date], placeholder: "Start Date", class: "form-control" %>
    </div>
    <div class="col-md-2">
      <%= text_field_tag :end_date, params[:end_date], placeholder: "End Date", class: 'form-control' %>
    </div>
    <div class="col-md-2">
      <%= submit_tag "Search", class: 'btn btn-primary' %>
    </div>
  </div>


<% end %>
<br>
<hr>
<br>

<div class="row">
  <div class="col-md-4">
    <h4>Homes</h4>
  </div>
</div>
  <div class="row">
    <% @rooms.each do |room| %>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading preview">
            <%= image_tag room.photos[0].image.url(:medium)if room.photos.length > 0 %>

          </div>
          <div class="panel-body">
            <p class="home-link"><b><%= link_to room.price, room_path(room) %> € - <%= link_to room.room_type, room_path(room) %> - <%= link_to pluralize(room.bed_room, "Bed"), room_path(room) %></b>
              <br><%= link_to room.listing_name, room_path(room) %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>



  <script>
      $(function() {
          $('#start_date').datepicker({
                      dateFormat: 'dd-mm-yy',
                      monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août',
                      'Septembre','Octobre','Novembre','Décembre'],
                      dayNamesMin: ['D','L','M','M','J','V','S'],
                      minDate: 0,
                      maxDate: '3m',
                      onSelect: function(selected) {
                          var newdate = new Date($("#start_date").datepicker("getDate"));
                          newdate.setDate(newdate.getDate() + 1);
                          $('#end_date').datepicker("option","minDate", newdate);
                      }
          })

          $('#end_date').datepicker({
                      dateFormat: 'dd-mm-yy',
                      monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août',
                      'Septembre','Octobre','Novembre','Décembre'],
                      dayNamesMin: ['D','L','M','M','J','V','S'],
                      minDate: 0,
                      maxDate: '3m',
                      onSelect: function(selected) {
                          $('#start_date').datepicker("option", "maxDate", selected);
                      }
          });
      })
  </script>

app/views/pages/search.html.erb
<div id="wrapper">
    <div id="sidebar">
        <div id="widget">
            <script>
                 function initMap() {
                   <% if @arrRooms.length > 0 %>
                       var uluru = {lat: <%= @arrRooms[0].latitude %>, lng: <%= @arrRooms[0].longitude %>};
                       var map = new google.maps.Map(document.getElementById('widget'), {
                         zoom: 13,
                         center: uluru
                       });
                   <% else %>
                       var uluru = {lat: 48.866667, lng: 2.333333};
                       var map = new google.maps.Map(document.getElementById('widget'), {
                         zoom: 4,
                         center: uluru
                       });
                   <% end %>

                   <% @arrRooms.each do |room| %>
                   var marker = new google.maps.Marker({
                     position: {lat: <%= room.latitude %>, lng: <%= room.longitude %>},
                     map: map,
                     title: "<%= room.listing_name %>"
                   });
                   <% end %>
                 }
               </script>
               <script async defer
               src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAiW9aBJM1x7XqmZiWKtADBfVjSXJmfV_k&callback=initMap">
               </script>
       </div>
        </div>
    </div>
    <div id="article">
        <div class="row">
            <div class="col-md-12">
                <%= search_form_for @search, url: search_path do |f| %>
                    <div class="row">
                        <div class="col-md-3">
                            <%= text_field_tag :start_date, params[:start_date], placeholder:"Start", class:"form-control" %>
                        </div>
                        <div class="col-md-3">
                            <%= text_field_tag :end_date, params[:end_date], placeholder:"End", class:"form-control" %>
                        </div>
                        <div class="col-md-3">
                            <%= f.text_field :price_gteq, placeholder: "Budget min", class: "form-control" %>
                        </div>
                        <div class="col-md-3">
                            <%= f.text_field :price_lteq, placeholder: "Budget max", class: "form-control" %>
                        </div>
                    </div>

                    <hr>

                    <div class="row">
                        <div class="col-md-4">
                            <%= check_box_tag "q[room_type_eq_any][]","Entire place" %> Entire place
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[room_type_eq_any][]","Private room" %> Private room
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[room_type_eq_any][]","Shared room" %> Shared room
                        </div>
                    </div>

                    <hr>

                    <div class="row">
                        <div class="col-md-4 select">
                            <div class="form-group">
                                <label> Guests number ?</label>
                                <%= f.select :accomodate, [["1 guest",1], ["2 guests",2],
                                ["3 guests", 3], ["4 guests",4], ["5 guests",5], ["6 guests",6]],
                                prompt: "Select it...", class: "form-control" %>
                            </div>
                        </div>

                        <div class="col-md-4 select">
                            <div class="form-group">
                                <label>Room(s)</label>
                                <%= f.select :bed_room, [["1 room",1], ["2 rooms",2],
                                ["3 rooms", 3], ["4 rooms or more",4]],
                                prompt: "Select a number", class: "form-control" %>
                            </div>
                        </div>

                        <div class="col-md-4 select">
                            <div class="form-group">
                                <label>Bath room(s)</label>
                                <%= f.select :bath_room, [["1 Bath room",1], ["2 Bath rooms",2],
                                ["3 Bath rooms", 3], ["4  Bath rooms or more",4]],
                                prompt: "Select a number", class: "form-control" %>
                            </div>
                        </div>
                    </div>

                    <hr>

                    <div class="row">
                        <div class="col-md-4">
                            <%= check_box_tag "q[is_wifi_eq]", true %> Wifi
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[is_tv_eq]", true %> TV
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[is_closet_eq]", true %> Closet
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[is_shampoo_eq]", true %> Shampoo
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[is_kitchen_eq]", true %> Kitchen
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[is_breakfast_eq]", true %> Breakfast
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[is_heating_eq]", true %> Heating
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[is_air_eq]", true %> A/C
                        </div>
                    </div>

                    <br>

                    <div class="row">
                        <%= f.submit "Search", class:"btn btn-primary" %>
                    </div>


                <% end %>

                <hr>



                <div class="row">
                    <% if @arrRooms.empty? %>
                        No listings for this search
                    <% else %>
                        <% @arrRooms.each do |room| %>
                        <div class="col-md-4">
                            <div class="panel panel-default">
                                <div class="panel-heading preview">
                                    <%= image_tag room.photos[0].image.url(:medium) if room.photos.length > 0 %>
                                </div>
                                <div class="panel-body">
                                    <%= image_tag avatar_url(room.user), class:"img-circle avatar-small" %>
                                    <%= link_to room.listing_name, room %>
                                </div>
                            </div>
                        </div>
                        <% end %>
                    <% end %>
                </div>

            </div>
        </div>
    </div>
</div>
<script>
    $(function() {
        $('#start_date').datepicker({
                    dateFormat: 'dd-mm-yy',
                    monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août',
                    'Septembre','Octobre','Novembre','Décembre'],
                    dayNamesMin: ['D','L','M','M','J','V','S'],
                    minDate: 0,
                    maxDate: '3m',
                    onSelect: function(selected) {
                        var newdate = new Date($("#start_date").datepicker("getDate"));
                        newdate.setDate(newdate.getDate() + 1);
                        $('#end_date').datepicker("option","minDate", newdate);
                    }
        })

        $('#end_date').datepicker({
                    dateFormat: 'dd-mm-yy',
                    monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août',
                    'Septembre','Octobre','Novembre','Décembre'],
                    dayNamesMin: ['D','L','M','M','J','V','S'],
                    minDate: 0,
                    maxDate: '3m',
                    onSelect: function(selected) {
                        $('#start_date').datepicker("option", "maxDate", selected);
                    }
        });
    })
</script>
<script>

 $(document).ready(function(){

           $("#sidebar").stick_in_parent({offset_top: 20});

 });

 </script>

app/views/shared/_devise_errors.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |msg| %>
      toast.error('<%= msg %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_errors.html.erb
<% unless @room.errors.empty? %>
  <script type="text/javascript">
    <% @room.errors.full_messages.each do |msg| %>
      toast.error('<%= msg %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
       <script type="text/javascript">
       <% flash.each do |f| %>
        <% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
         toastr['<%= type %>']('<%= f[1] %>')
       <% end %>
       </script>
 <% end %>